/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as EmailRouteImport } from './routes/email'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as ExportacoesRouteImport } from './routes/exportacoes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MinhasEmpresasRouteImport } from './routes/minhas-empresas'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as SociosRouteImport } from './routes/socios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportacoesRoute = ExportacoesRouteImport.update({
  id: '/exportacoes',
  path: '/exportacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasEmpresasRoute = MinhasEmpresasRouteImport.update({
  id: '/minhas-empresas',
  path: '/minhas-empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const SociosRoute = SociosRouteImport.update({
  id: '/socios',
  path: '/socios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/email': typeof EmailRoute
  '/empresas': typeof EmpresasRoute
  '/exportacoes': typeof ExportacoesRoute
  '/login': typeof LoginRoute
  '/minhas-empresas': typeof MinhasEmpresasRoute
  '/perfil': typeof PerfilRoute
  '/socios': typeof SociosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/email': typeof EmailRoute
  '/empresas': typeof EmpresasRoute
  '/exportacoes': typeof ExportacoesRoute
  '/login': typeof LoginRoute
  '/minhas-empresas': typeof MinhasEmpresasRoute
  '/perfil': typeof PerfilRoute
  '/socios': typeof SociosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/email': typeof EmailRoute
  '/empresas': typeof EmpresasRoute
  '/exportacoes': typeof ExportacoesRoute
  '/login': typeof LoginRoute
  '/minhas-empresas': typeof MinhasEmpresasRoute
  '/perfil': typeof PerfilRoute
  '/socios': typeof SociosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/cadastro'
    | '/configuracoes'
    | '/email'
    | '/empresas'
    | '/exportacoes'
    | '/login'
    | '/minhas-empresas'
    | '/perfil'
    | '/socios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/cadastro'
    | '/configuracoes'
    | '/email'
    | '/empresas'
    | '/exportacoes'
    | '/login'
    | '/minhas-empresas'
    | '/perfil'
    | '/socios'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/cadastro'
    | '/configuracoes'
    | '/email'
    | '/empresas'
    | '/exportacoes'
    | '/login'
    | '/minhas-empresas'
    | '/perfil'
    | '/socios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  CadastroRoute: typeof CadastroRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EmailRoute: typeof EmailRoute
  EmpresasRoute: typeof EmpresasRoute
  ExportacoesRoute: typeof ExportacoesRoute
  LoginRoute: typeof LoginRoute
  MinhasEmpresasRoute: typeof MinhasEmpresasRoute
  PerfilRoute: typeof PerfilRoute
  SociosRoute: typeof SociosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exportacoes': {
      id: '/exportacoes'
      path: '/exportacoes'
      fullPath: '/exportacoes'
      preLoaderRoute: typeof ExportacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-empresas': {
      id: '/minhas-empresas'
      path: '/minhas-empresas'
      fullPath: '/minhas-empresas'
      preLoaderRoute: typeof MinhasEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/socios': {
      id: '/socios'
      path: '/socios'
      fullPath: '/socios'
      preLoaderRoute: typeof SociosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  CadastroRoute: CadastroRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EmailRoute: EmailRoute,
  EmpresasRoute: EmpresasRoute,
  ExportacoesRoute: ExportacoesRoute,
  LoginRoute: LoginRoute,
  MinhasEmpresasRoute: MinhasEmpresasRoute,
  PerfilRoute: PerfilRoute,
  SociosRoute: SociosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
